table Dates
	lineageTag: 3d0e251f-6eb5-4ee2-b698-cf8108e4b3be

	column 'Day Name'
		dataType: string
		lineageTag: dbcee415-2bb2-4a07-bb09-7be566292f52
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: e9288253-803e-41ed-ac35-b445aa941dc6
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: int64
		formatString: 0
		lineageTag: 46437f90-c35b-44fe-a2cb-db6459b8b599
		summarizeBy: sum
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 460fe179-2670-457a-8769-0799f6d768c8
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 27336b97-e89c-402e-b109-f3ebb1be7300
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 538dab32-668d-4460-86f1-cac91f6becec
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 88c82cf5-8195-4fbe-baf6-33dca2146959
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 63d98426-3607-4b10-ab4f-5c1035fe34e7
			defaultHierarchy: LocalDateTable_33c53907-8667-4d95-80d7-8cf65ed80b80.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition Dates = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Souradeep Singha\Downloads\0bon\QUESTION_Connection2POWERBI.xlsx"), null, true),
				    Dates_Sheet = Source{[Item="Dates",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Dates_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", Int64.Type}, {"Day Name", type text}, {"Day", Int64.Type}, {"Week", Int64.Type}, {"Month", Int64.Type}, {"Quarter", Int64.Type}, {"Year", Int64.Type}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type any}, {"Column26", type any}, {"Column27", type any}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Day Name", type text}}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Changed Type1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Blank Rows",{"Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Columns",{{"Date", type datetime}})
				in
				    #"Changed Type2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

